services:
  lgtm:
    image: grafana/otel-lgtm:latest
    container_name: nova-observability-lgtm

    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"

    volumes:
      - nova-lgtm-data:/data
      - ./provisioning/dashboards/nova.yaml:/otel-lgtm/grafana/conf/provisioning/dashboards/nova.yaml:ro
      - ./dashboards:/otel-lgtm/grafana/conf/provisioning/dashboards/nova:ro

    restart: unless-stopped

volumes:
  nova-lgtm-data:
