<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>

		<AssemblyName>Nova.Observability.Messaging</AssemblyName>
		<RootNamespace>Nova.Observability.Messaging</RootNamespace>

		<Description>
			Messaging trace context propagation and instrumentation for Nova Observability.
		</Description>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Nova.Observability.Abstractions\Nova.Observability.Abstractions.csproj" />

		<ProjectReference Include="..\Nova.Observability.Core\Nova.Observability.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="OpenTelemetry.Api" />
	</ItemGroup>

</Project>