<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net462;net48</TargetFrameworks>

		<AssemblyName>Nova.Observability.Legacy</AssemblyName>
		<RootNamespace>Nova.Observability.Legacy</RootNamespace>

		<Description>
			App.config and non-DI bootstrap integration for .NET Framework applications.
		</Description>

		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference
		  Include="..\Nova.Observability.Abstractions\Nova.Observability.Abstractions.csproj" />

		<ProjectReference
		  Include="..\Nova.Observability.Core\Nova.Observability.Core.csproj" />

		<ProjectReference
		  Include="..\Nova.Observability.OpenTelemetry\Nova.Observability.OpenTelemetry.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference
		  Include="Microsoft.NETFramework.ReferenceAssemblies"
		  PrivateAssets="all" />
	</ItemGroup>

</Project>