<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion
      Include="System.Diagnostics.DiagnosticSource"
      Version="10.0.10" />

    <PackageVersion
      Include="OpenTelemetry"
      Version="1.17.0" />

    <PackageVersion
      Include="OpenTelemetry.Extensions.Hosting"
      Version="1.17.0" />

    <PackageVersion
      Include="OpenTelemetry.Exporter.OpenTelemetryProtocol"
      Version="1.17.0" />

    <PackageVersion
      Include="Microsoft.Extensions.Hosting.Abstractions"
      Version="10.0.10" />

    <PackageVersion
      Include="Microsoft.Extensions.DependencyInjection.Abstractions"
      Version="10.0.10" />

    <PackageVersion
      Include="Microsoft.Extensions.Logging.Abstractions"
      Version="10.0.10" />

    <PackageVersion
      Include="Microsoft.NETFramework.ReferenceAssemblies"
      Version="1.0.3" />
  </ItemGroup>

</Project>